# Site settings
title: CTYI Web Development
email: ctyi@dcu.ie
description: > # this means to ignore newlines until "baseurl:"
  A collection of HTML, CSS and JS resources used by CTYI instructors over the years.
baseurl: "/ctyiwebdev" # the subpath of your site, e.g. /blog/
url: "http://domhnallohanlon.github.io" # the base hostname & protocol for your site
twitter_username: domhnallohanlon
github_username:  domhnallohanlon

# Build settings
markdown: kramdown
